### ISSUE TITLE
Permission denied when installing kernelspec

### ISSUE THREAD

**Issue by vaibhavsagar** [jupyter/docker-demo-images#104]
I'm trying to update the IHaskell configuration and I'm running into this error:

```
Exception: error running: /opt/conda/bin/jupyter kernelspec install --user /tmp/tmpThreadId41804289383846930886/has
kell --replace
exit status: 1
stderr: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter/kernels/haskell'
```

I haven't made any changes other than bumping some versions but I can share my modified `Dockerfile` if that would help.

**Comment by vaibhavsagar** [comment]
I've worked around this in #105, but if there is a better way I would love to do that instead.

**Comment by Carreau** [comment]
The error is weird. 
Let's try to see if we can figure out the permission of `/home/jovyan/.local/share/jupyter/kernels/` during build, otherwise I think the `USER root` permission should be acceptable.

**Comment by vaibhavsagar** [comment]
As pointed out in the linked PR, the solution was to specify `--prefix=$CONDA_DIR`.
