### ISSUE TITLE
Deprecate in favor of docker stacks & binder

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/docker-demo-images#106]
Ideally, we should be completely switched over to binder and relying on well curated stacks for docker. Since people can create their own images by making new repos, they can feature their tool or kernel there.

**Comment by parente** [comment]
@minrk had mentioned creating one or more binder example repos to take the place of try.jupyter.org, maybe in here https://github.com/binder-examples?

Relate: I'm slowly picking away at a first PR for https://github.com/jupyter/docker-stacks/issues/517 to setup a proper docs site for docker-stacks, including info on people can create their own repos. The binder docs site has guidance for using Dockerfiles too: https://mybinder.readthedocs.io/en/latest/dockerfile.html

**Comment by minrk** [comment]
The switch to Binder is complete.
