### ISSUE TITLE
R packages in tmpnb.org

### ISSUE THREAD

**Issue by stonebig** [jupyter/docker-demo-images#14]
hi,

I notice that "dplyr" doesn't show up on a today tmpnb.org temporary notebook.
If we follow recent Hadley Whickam  push on SQL, it may be pertinent to include also a basic SQL motor, like  `RSQLite`.

on my personnal demo set, I added also:
- "hflights"  and "nycflights13" for typical datasets of demo used by Hadley,
-  "forecast" and "zoo", but that may start to be too heavy for tmpnb.org

**Comment by willingc** [comment]
@parente I'm going to close this issue since the [Jupyter Notebook R Docker Stack](https://github.com/jupyter/docker-stacks/tree/master/r-notebook) is now available.

@stonebig Thanks for the earlier feedback :)
