### ISSUE TITLE
Julia Packages in tmpnb.org

### ISSUE THREAD

**Issue by stonebig** [jupyter/docker-demo-images#15]
Hi,

Looking at the list of Julia packages via `Pkg.status()`, I Would suggest to add:
- PyCall
- PyPlot
- Interact
- Sympy
- SQLite

**Comment by willingc** [comment]
@parente @stonebig I'm going to close this since there is now a Julia demo notebook and ongoing work on the Docker Stack in the [docker-stacks](https://github.com/jupyter/docker-stacks).

**Comment by parente** [comment]
@stonebig We could add them to the jupyter/datascience-notebook stack if you think they're very common packages when working in Julia.

**Comment by stonebig** [comment]
hi @parente , I didn't have time to follow Julia since a year. Do what you thing right.
