### ISSUE TITLE
Add Rackspace logo to default image we serve on try.jupyter.org

### ISSUE THREAD

**Issue by fperez** [jupyter/docker-demo-images#24]
I think we should acknowledge Rackspace's contribution to try.jupyter in a more public/visible fashion, by having a visible logo (much like it was done for the Nature demo).

In the future, if we have a more 'federated' model with other providers also hosting official try.jupyter instances, we can figure out how to properly acknowledge them all as well, obviously. But might as well start by doing the n=1 case right :)

Thoughts?

**Comment by fperez** [comment]
Says @rgbkrk on the closed issue that started this:

> Awesome, thank you. I've been hoping that we skin it too as well as provide an advisory about the temporaryness of their session. Perhaps a custom template across all the pages? We already inject Google Analytics on all the pages.

**Comment by Carreau** [comment]
Want to replace the Jupyter Logo By `Jupyter on Rackspace`?

**Comment by fperez** [comment]
I was thinking more of having a separate logo are for 'hosted by X', where for now X is Rackspace. That would also make it easier to have other vendors acknowledged, if in the future we federate out.  Simpler to do that than to have to create custom images that mix Jupyter + company.

**Comment by rgbkrk** [comment]
Done in #36.
