### ISSUE TITLE
docker build ends with error in download: client error: 404

### ISSUE THREAD

**Issue by wenzeslaus** [jupyter/docker-demo-images#25]
After:

    git clone git@github.com:jupyter/docker-demo-images.git
    cd docker-demo-images/
    sudo docker build -t jupyter/demo .

or:

    sudo docker build -t jupyter/minimal .

I get:

    Downloading github repo armstrtw/rzmq@master
    Installing rzmq
    '/usr/lib/R/bin/R' --vanilla CMD INSTALL  \
      '/tmp/Rtmp0PqtK9/devtools763eddacb/armstrtw-rzmq-45f0d94'  \
      --library='/home/jovyan/.R' --install-tests 

    * installing *source* package ‘rzmq’ ...
    ** libs
    g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/cppzmq    '-std=c++11' -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c interface.cpp -o interface.o
    g++ -std=c++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o rzmq.so interface.o -lzmq -L/usr/lib/R/lib -lR
    installing to /home/jovyan/.R/rzmq/libs
    ** R
    ** inst
    ** tests
    ** preparing package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** testing if installed package can be loaded
    * DONE (rzmq)
    Downloading github repo takluyver/IRdisplay@master
    Error in download(dest, src, auth) : client error: (404) Not Found
    Calls: install_github ... remote_download.github_remote -> download -> <Anonymous>
    Execution halted
    2015/04/01 15:16:04 The command [/bin/sh -c echo "library(devtools); install_github('armstrtw/rzmq'); install_github('takluyver/IRdisplay'); install_github('takluyver/IRkernel'); IRkernel::installspec()" | R --no-save] returned a non-zero code: 1

I expected that using the Dockerfile from repository will just work. Do I miss something?

**Comment by Carreau** [comment]
Repo has moved. Docker just not following redirect. it os there I guess `https://github.com/IRkernel/IRdisplay` do you want to make a PR ?

**Comment by wenzeslaus** [comment]
Thanks. It builds well now.
