### ISSUE TITLE
Strange fonts on try.jupyter.org

### ISSUE THREAD

**Issue by sumitsahrawat** [jupyter/docker-demo-images#38]
![screenshot from 2015-05-10 11-12-32](https://cloud.githubusercontent.com/assets/5645741/7553194/86cc89e0-f705-11e4-996e-8ba5982a50e6.png)

This is an example from the `Welcome R - demo.ipynb` notebook.

**Comment by rgbkrk** [comment]
Hmmmm, that must have come from either our recent addition of `apt-get clean` or the build of R packages /cc @asmeurer

**Comment by sumitsahrawat** [comment]
Quoting `man apt-get`

```
  clean
      clean clears out the local repository of retrieved package files.
      It removes everything but the lock file from
      /var/cache/apt/archives/ and /var/cache/apt/archives/partial/.
```

As it only removes cached package files (from `/var/cache/apt/archives`), this should not be an issue.

**Comment by asmeurer** [comment]
What browser are you using? There are apparently some issues with the R kernel plots and Firefox.

**Comment by sumitsahrawat** [comment]
I'm using Google Chrome. Here's more info

![screenshot from 2015-05-10 23-02-40](https://cloud.githubusercontent.com/assets/5645741/7555427/b3613678-f768-11e4-873a-000d1232a319.png)

**Comment by asmeurer** [comment]
It renders correctly for me in Version 43.0.2357.52 beta (64-bit) (OS X 10.10.4).

**Comment by asmeurer** [comment]
I tried Firefox, but it wouldn't even let me go to try.jupyter.org ("This connection is untrusted").

**Comment by sumitsahrawat** [comment]
I got even strange results with firefox 35.0.1 (in a ubuntu 14.04 VM).

![screenshot from 2015-05-11 01-03-36](https://cloud.githubusercontent.com/assets/5645741/7555915/9a7e78e4-f779-11e4-8225-7a13fbc14d78.png)

The fonts are barely visible.

**Comment by sumitsahrawat** [comment]
From the same VM, *chromium* 41.0.2272.76 (Developer Build) renders it well.

![screenshot from 2015-05-11 01-15-36](https://cloud.githubusercontent.com/assets/5645741/7555967/442dbff2-f77b-11e4-9dd6-d41405103fec.png)

**Comment by asmeurer** [comment]
So this is likely an upstream problem with IRkernel/IRdisplay. I think they are using svg, which has issues with some browsers.

**Comment by sumitsahrawat** [comment]
Closing this, as it's a browser specific issue.

**Comment by rgbkrk** [comment]
Can you try tmpnb.org @asmeurer (same system, different certs)?

**Comment by asmeurer** [comment]
I see now. I didn't realize this was coming from the example notebook. For me, it works if I only execute the cell with the plot, but if I execute the earlier cells first, I get the same result as @sumitsahrawat (even in Chrome).
