### ISSUE TITLE
Allow posting anonymous or logged in gists

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/docker-demo-images#4]
This is the right spot for https://github.com/jupyter/tmpnb/issues/37 now.

Use @minrk's notebook extension for sharing a gist, a la https://github.com/jupyter/tmpnb/pull/70. The extension needs an update to do anonymous gist posting. Since you can't update an anonymous gist, we'd want to make it at least a little awkward to post an update so we're not filling GitHub up. :wink:

**Comment by willingc** [comment]
@rgbkrk @parente Can this be closed?

**Comment by rgbkrk** [comment]
I think we can reasonably say we're not about to do this anytime soon. We can close it and re-open if we re-visit. We've got architectural things to solve with the frontend before we can deploy this safely.
