### ISSUE TITLE
pyspark

### ISSUE THREAD

**Issue by nymoorland** [jupyter/docker-demo-images#41]
Add pyspark. I think you mentioned this is in there now?

**Comment by rgbkrk** [comment]
In order for us to do this we'd need a Spark environment (or so I think).

**Comment by nymoorland** [comment]
Or maybe this. https://github.com/minrk/findspark @minrk

**Comment by rgbkrk** [comment]
Oh hey, that's neat.

**Comment by parente** [comment]
The associated PR adds local mode Spark 1.4.0 support for both Python 3 and Scala 2.10 kernels in the "kitchen sink" tmpnb.org image.

**Comment by parente** [comment]
There's now also a pyspark-notebook and all-spark-notebook stack (w/ pyspark) in https://github.com/jupyter/docker-stacks and https://hub.docker.com/u/jupyter. I think we can close but please reopen if I missed something.

**Comment by nymoorland** [comment]
@parente You are doing some awesome stuff with Docker stacks. Your work and attention to detail is much appreciated! Already so many pulls. This has been much needed for a long time. Nice job!
