### ISSUE TITLE
bash kernel not loading.  Need to update to two step process

### ISSUE THREAD

**Issue by kbroughton** [jupyter/docker-demo-images#64]
The process for installing a bash kernel changed 14 days ago.
The Dockerfile for the demo image needs updating to reflect this
https://github.com/takluyver/bash_kernel/blame/master/README.rst
RUN python -m bash_kernel.install

**Comment by parente** [comment]
Resolved by #71 which installs the bash kernel. For reference, https://github.com/jupyter/docker-stacks/issues/25#issuecomment-139444841 has a Dockerfile with the commands to install the bash kernel alone.
