### ISSUE TITLE
container bloat for demo image

### ISSUE THREAD

**Issue by kbroughton** [jupyter/docker-demo-images#65]
The pull of the container from 2 weeks ago jumped from 2.5 Gb to 6 Gb.  
Why is that?
$ docker images | grep jup
jupyter/demo                                        latest                   d6449de4bebe        2 weeks ago         6.234 GB
jupyter/notebook                                    latest                   c9a1d70bfcdf        3 weeks ago         910.2 MB
jupyter/minimal                                     latest                   9c79b1043d59        5 weeks ago         1.184 GB
jupyter/demo                                        clean                    66f14ab192df        3 months ago        2.578 GB
jupyter/demo-minimal                                latest                   98b7aad170f6        9 months ago        791.2 MB

We are trying to customize the container based on jupyter/demo and the builds are failing on pushing to the registry with out of disk space errors.

**Comment by rgbkrk** [comment]
Yeah that's kind of weighty. If I had to guess, that's the new Spark stuff. /cc @parente 

We haven't built an uploaded this one yet due to transitions to Jupyter 4.0

**Comment by parente** [comment]
Before I rebuilt the image with Scala + Spark, I measured it at ~5GB. I'll double-check if I can find the SHA.

At any rate, I agree the image is massive, but intentionally: it's meant to be a demo of the multi-language support of Jupyter. If smaller images are desired for other purposes, I think they belong in jupyter/docker-stacks.

**Comment by parente** [comment]
Commit ccfa2724, just before the Scala kernel and Spark support for Scala and Python3 went in builds as:

`jupyter/demo                 latest              edd16f44e83e        11 seconds ago      5.409 GB`

After:

`jupyter/demo                 stable              e0b0cab62986        6 weeks ago         6.186 GB`

**Comment by parente** [comment]
Is there any action to take on this item?

**Comment by kbroughton** [comment]
I don't think so.  You might point in the Readme to the docker-stacks repo for anyone looking for a more minimal container docker-stacks/minimal-notebook

**Comment by parente** [comment]
Good idea. I was thinking about a FAQ in the README with other content as well. I'll work it in.

**Comment by rgbkrk** [comment]
One point I'm realizing out of this - with multiple tags, if people do `docker pull jupyter/demo` they're getting *all* these mega images.

**Comment by parente** [comment]
With older docker clients, yes. Modern docker (I forget which version) only pulls latest by default unless you specify `--all` on the pull.

**Comment by rgbkrk** [comment]
ohhhh, neat

**Comment by parente** [comment]
I think we can close this. There's now a FAQ with pointers to docker-stacks.
