### ISSUE TITLE
Rebase on jupyter/minimal-notebook:4.0

### ISSUE THREAD

**Issue by parente** [jupyter/docker-demo-images#67]
@rgbkrk and I discussed briefly rebasing the minimal-image and demo-image defined in this repo on the https://github.com/jupyter/docker-stacks/minimal-notebook 4.0.x base image once all the kernels in the demo image can support 4.0.

Why?

* Common base to maintain
* Probably don't need minimal-image vs demo-image separation anymore
  * Strawman: jupyter/try-jupyter-notebook which has the specific config for that site
* Suggest that others build their own image from stacks following the pattern here OR invest effort in making it easy for folks to customize the image here with their own branding for their own tmpnb setup.

**Comment by parente** [comment]
PR #71

**Comment by rgbkrk** [comment]
Sweet thanks

**Comment by parente** [comment]
#71 is merged. tmpnb.org will be updated in the near future with the image.
