### ISSUE TITLE
docker build -t <tag> . broken still.  Line 36... kernelspec install-self --user

### ISSUE THREAD

**Issue by kbroughton** [jupyter/docker-demo-images#68]
Is anybody else seeing this?  I've tried on mac and unix.  Both break at the same location on a fresh clone and build.  This has been broken for the last 2 weeks.  Anyone know what the last passing commit was?

docker-demo-images/ ] docker build -t jupyterdemolocal .

...
removing itsdangerous-0.24-py27_0.tar.bz2
 ---> d17a757c74ef
Removing intermediate container bc1e883d34da
Step 36 : RUN $CONDA_DIR/envs/python2/bin/python $CONDA_DIR/envs/python2/bin/ipython kernelspec install-self --user
 ---> Running in 6c7110207ad2
Traceback (most recent call last):
  File "/opt/conda/envs/python2/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named jupyter_client.kernelspecapp
The command '/bin/sh -c $CONDA_DIR/envs/python2/bin/python $CONDA_DIR/envs/python2/bin/ipython kernelspec install-self --user' returned a non-zero code: 1

**Comment by kbroughton** [comment]
automated builds for this repo jupyter/demo (top level Dockerfile) doesn't exist and for jupyter/demo-minimal has been failing since nov 2014
https://hub.docker.com/r/jupyter/demo-minimal/builds/

**Comment by parente** [comment]
The Dockerfiles in this repo do not pin library version numbers. So (best guess) what I expect is happening is a version mismatch between the notebook server that some RUN command further up in the Dockerfile (or in the minimal-demo base Dockerfile) installed and what the python2 environment specifically installed.

@rgbkrk AI opened #67 to start moving in the direction of pinning like we do in docker-stacks across the board. But is there a way you'd like to handle in the near term?

**Comment by snowch** [comment]
I'm hitting this issue as well.  Is there a workaround?

**Comment by gwtaylor** [comment]
I ran into this too, both here and on https://github.com/rothnic/anaconda-notebook. I found that a quick fix was to tell ```conda-install``` to explicitly install IPython 3 (rothnic/anaconda-notebook#5). I think a better solution is to update the whole image to install ``jupyter`` instead.

**Comment by parente** [comment]
As soon as we fix up some problems with the images over in jupyter/docker-stacks, I hope to get to issue #67 which will rebase the docker-demo-image on the jupyter/minimal-notebook:4.0 image and resolve these problems along the way.

I don't yet know if all the kernels in the current demo image support jupyter 4.0 yet though. If not, we'll either have to remove them or wait until they all do.

**Comment by kbroughton** [comment]
I noticed that recent additions of Jupiter docker stacks have removed the
creation of the Jovian user to the startup script. This makes it a little
more difficult to extend the container since the directories where you
would like to place things no longer exist at build time. It also seems to
make it harder to make the containers immutable and more likely that you
need to install things during the run time part which defeats the
immutability of containers. Is there a good pattern for extending the
containers? Normally my approach would be to try and keep the  command
script as small as possible so that containers are almost completely
immutable.

**Comment by parente** [comment]
I'm busy restoring the user creation in the docker container right now but allowing the Jovian uid to change in the startup script. Once we have the best of both worlds, extension should be as expected in the dockerfile. The various subimages in the stacks repo will be reasonable examples.

**Comment by snowch** [comment]
@gwtaylor - thanks for the info.  It looks as though the changes got me past the error listed above, but I have run into another error so can't be sure.

```diff
diff --git a/Dockerfile b/Dockerfile
index 1fe8352..f82c3d4 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -77,7 +77,7 @@ USER jovyan
 RUN conda install --yes numpy pandas scikit-learn scikit-image matplotlib scipy seaborn sympy cython patsy statsmodels cloudpickle dill numba bokeh && conda clean -yt
 
 # Now for a python2 environment
-RUN conda create -p $CONDA_DIR/envs/python2 python=2.7 ipython numpy pandas scikit-learn scikit-image matplotlib scipy seaborn sympy cython patsy statsmodels cloudpickle dill numba bokeh && conda clean -yt
+RUN conda create -p $CONDA_DIR/envs/python2 python=2.7 ipython=3.2.1 numpy pandas scikit-learn scikit-image matplotlib scipy seaborn sympy cython patsy statsmodels cloudpickle dill numba bokeh && conda clean -yt
 RUN $CONDA_DIR/envs/python2/bin/python $CONDA_DIR/envs/python2/bin/ipython kernelspec install-self --user
 
 # IRuby
```

The next error I get is:

```bash
In-place registering ihaskell-0.6.4.1...
Preprocessing executable 'ihaskell' for ihaskell-0.6.4.1...
[1 of 2] Compiling IHaskellPrelude  ( main/IHaskellPrelude.hs, dist/build/ihaskell/ihaskell-tmp/IHaskellPrelude.o )
[2 of 2] Compiling Main             ( main/Main.hs, dist/build/ihaskell/ihaskell-tmp/Main.o )

main/Main.hs:204:17:
    `language' is not a (visible) field of constructor `KernelInfoReply'

main/Main.hs:205:17:
    `versionList' is not a (visible) field of constructor `KernelInfoReply'
Failed to install ihaskell-0.6.4.1
cabal: Error: some packages failed to install:
ihaskell-0.6.4.1 failed during the building phase. The exception was:
ExitFailure 1
The command '/bin/sh -c cabal update &&     cabal install cpphs &&     cabal install gtk2hs-buildtools &&     cabal install ihaskell-0.6.4.1 --reorder-goals &&     cabal install ihaskell-widgets-0.1 HTTP Chart Chart-cairo &&     ihaskell install &&     rm -fr $(echo ~/.cabal/bin/* | grep -iv ihaskell) ~/.cabal/packages ~/.cabal/share/doc ~/.cabal/setup-exe-cache ~/.cabal/logs' returned a non-zero code: 1
```

**Comment by parente** [comment]
All build errors should be resolved now that #71 is in. We can leave this issue open until someone else is able to confirm a fresh build works.

There's also a new PR #73 to prevent future builds of the haskell portions from running into new errors. As of yesterday, the minor version pinning we've done for the IHaskell dependencies were enough to get a successful build.

**Comment by rgbkrk** [comment]
Certainly working for me, new versions getting pushed out now that Peter is helping me too.

**Comment by parente** [comment]
I rebuilt master today to see how it's aged over two weeks. No problems.
