### ISSUE TITLE
Allow try.jupyter.org to use as jupyter plugins demo

### ISSUE THREAD

**Issue by lambdalisue** [jupyter/docker-demo-images#81]
Hi. First of all, thanks for the entire jupyter project. I really addicted to this project and I built a jupter plugin to allow users to use Vim key bindings ([jupyter-vim-binding](https://github.com/lambdalisue/jupyter-vim-binding)).

So I wonder if I can share a live demo of my plugin without preparing a server.
I heared that there is a live demo of Jupyter (https://try.jyputer.org) but **of course** `install_nbextension` did not work and it seemed that there is no way to embed an external plugin.

So could you consider about preparing a official way to share a live demo of jupyter plugin whenever you have time? I understand it may cause some security risks and that makes things hard to implement but I believe it would be really nice if user can try the latest plugin in a live demo.

Not only for my plugin but also for [a lot of plugins in the world](https://github.com/ipython-contrib/IPython-notebook-extensions).

Thanks :-)

Ref: https://github.com/lambdalisue/jupyter-vim-binding/issues/22

**Comment by minrk** [comment]
try.jupyter is pretty restricted, but if you want to put up your own demo instance, you can give [binder](http://mybinder.org) a try. It's like deploying your own try.jupyter instance, where you get to specify extra things to install.

**Comment by lambdalisue** [comment]
Wow. Thanks for pointing me to that :smile: I'll check it out.
