### ISSUE TITLE
use apache toree

### ISSUE THREAD

**Issue by minrk** [jupyter/docker-demo-images#86]
we are still using the spark-kernel package, but should update to use toree.

@parente should we switch the base image from minimal to one of the spark-including stacks, rather than duplicate that installation here?

**Comment by parente** [comment]
I was thinking about that. We could start from all-spark-notebook. It'll require some rejiggering of the dockerfile here. Or we can just keep the spark links here + the pip install for toree.

Probably want to try starting from all-spark-notebook and see how much that impacts the dockerfile here.

**Comment by minrk** [comment]
Starting from all-spark sounds like a good idea.

I only just now realized all-spark might be a [transformers reference](https://en.wikipedia.org/wiki/allspark).

**Comment by parente** [comment]
> I only just now realized all-spark might be a transformers reference.

I snuck the name in there back in July and waited many long months for someone to catch it. You're the third person. 🏆

**Comment by jakirkham** [comment]
> You're the third person. 🏆

Does something magical happen now? 🌠

**Comment by parente** [comment]
What? A trophy emoji isn't magical enough for you? Fine.

![http://33.media.tumblr.com/d22df165e7ed8bfd2426c9b3d0af4baa/tumblr_inline_n13tu3bk6m1sxje2l.gif](http://33.media.tumblr.com/d22df165e7ed8bfd2426c9b3d0af4baa/tumblr_inline_n13tu3bk6m1sxje2l.gif)
