### ISSUE TITLE
re-enable sciruby

### ISSUE THREAD

**Issue by minrk** [jupyter/docker-demo-images#88]
sciruby (0.2.8) isn't currently installable due to a dependency conflict (SciRuby/sciruby#49). As a result, sciruby is currently disabled in the demo image. Once sciruby is installable, we should re-enable it.

There may be a fix right now, but when I tried the obvious choice of pinning mixed_models to 0.1.0 (0.1.1 is where the conflict is introduced):

    gem install mixed_models:0.1.0 sciruby-full

gem just hangs, possibly in an infinite loop trying to solve the dependency graph.

**Comment by minad** [comment]
should work again

**Comment by minrk** [comment]
@minad thanks! I'll test and add it back.

**Comment by minrk** [comment]
@minad confirmed that it works, thanks! I'll push it out to try.jupyter before too long.

**Comment by minad** [comment]
It should also never break again™ since I imposed rigid version constraints.
