### ISSUE TITLE
Should this repo be considered "User Engagement" or "Services"?

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/docker-demo-images#95]
@parente @minrk : How should this repo be categorized? Fernando and Brian suggested "User Engagement" or "Services". Please let me know which one of these is most appropriate or if there's another category under which it should be listed. 

Thanks!

**Comment by parente** [comment]
Both if that's an option. :)

**Comment by minrk** [comment]
We deploy this image as a service (try.jupyter.org), but the point of that service is introducing Jupyter to new users. Not sure if that helps.
