### ISSUE TITLE
Requesting Tensorflow

### ISSUE THREAD

**Issue by pichonz** [jupyter/docker-demo-images#97]
I'm not sure if this is the right place but it would be really nice if try.jupyter.org would have tensorflow available for its users. Windows folks would specially be thankful while we wait for native support .

**Comment by parente** [comment]
There's a tensorflow image in the jupyter/docker-stacks project if you have docker locally. Or maybe we can rebase this image on that one to get it to the try site as well

**Comment by pichonz** [comment]
If you can get it to the try site, that wold be awesome!

**Comment by minrk** [comment]
tensorflow can be used on Binder. There isn't an example yet, but one could be added to https://jupyter.org/try
